sonar.projectKey=ifds-image-forgery
sonar.projectName=Image Forgery Detection System
sonar.projectVersion=1.0
sonar.sources=src,app.py,ui,config
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.10
sonar.exclusions=data/**,docs/doxygen/**,**/__pycache__/**
sonar.coverage.exclusions=tests/**,src/training/**
