"""
@file settings.py
@brief Global configuration constants for the IFDS application.
"""

from __future__ import annotations

from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"
MODELS_DIR = DATA_DIR / "models"

XCEPTION_INPUT_SIZE = (224, 224)
EFFICIENTNET_INPUT_SIZE = (224, 224)
LSTM_INPUT_SIZE = (256, 256)
PATCH_SIZE = (32, 32)
GRID_SIZE = 8
SEQUENCE_LENGTH = GRID_SIZE * GRID_SIZE
EFFICIENTNET_VARIANT = "B0"

BATCH_SIZE = 32
EPOCHS_XCEPTION = 20
EPOCHS_LSTM = 15
LEARNING_RATE = 1e-4
FINE_TUNE_LAYERS = 20

TRAIN_RATIO = 0.70
VAL_RATIO = 0.15
TEST_RATIO = 0.15
RANDOM_STATE = 42

SUPPORTED_FORMATS = {".jpg", ".jpeg", ".png", ".gif", ".bmp", ".tiff", ".tif"}
STREAMLIT_UPLOAD_EXTENSIONS = ["jpg", "jpeg", "png", "gif", "bmp", "tiff", "tif"]
MAX_FILE_SIZE_MB = 50
MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024

CLASS_AUTHENTIC = 0
CLASS_TAMPERED = 1
CLASS_NAMES = ["Authentic", "Tampered"]
CONFIDENCE_THRESHOLD = 0.5
XCEPTION_DECISION_THRESHOLD = 0.58
EFFICIENTNET_DECISION_THRESHOLD = 0.5

SIFT_MIN_MATCHES = 10
SURF_MIN_MATCHES = 10
AKAZE_MIN_MATCHES = 8
ORB_MIN_MATCHES = 12
LOWE_RATIO_FLOAT = 0.75
LOWE_RATIO_BINARY = 0.80
MIN_DISPLACEMENT_PX = 8.0
RANSAC_REPROJECTION_THRESHOLD = 5.0

CLASSICAL_TARGET_SECONDS = 5.0
AI_TARGET_SECONDS = 10.0
MIN_TEST_COVERAGE = 70

XCEPTION_MODEL_PATH = MODELS_DIR / "xception_finetuned.h5"
EFFICIENTNET_MODEL_PATH = MODELS_DIR / "efficientnet_finetuned.h5"
LSTM_MODEL_PATH = EFFICIENTNET_MODEL_PATH

PRIMARY_COLOR = "#1F3864"
SECONDARY_COLOR = "#2E75B6"
SUCCESS_COLOR = "#1B7F4C"
ERROR_COLOR = "#B42318"
